- hosts: 127.0.0.1
  vars:
    my_name: "Peter"
  tasks:
    - name: Copy a template to a certain destination.
      ansible.builtin.template:
        src: ./index_template.html
        dest: ./index.html
